// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnwdytxuqqrbntkfkggu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRud2R5dHh1cXFyYm50a2ZrZ2d1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQxNzgzODAsImV4cCI6MjA0OTc1NDM4MH0.gEXx0T41GRBeUZjNCR1Yb0SCXEjWgsRB7uuc3pc8vxI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);